### ISSUE TITLE
微信公众号文章图片无法加载，需补充 Host

### ISSUE THREAD

**Issue by z4jst** [ydzydzydz/Rules#1]
qpic.cn 如果使用配置中的 DNS 会导致无法加载图片，需要在 host 中加入如下片段。
[Host]

// 微信
*.qpic.cn = server:119.28.28.28

**Comment by ydzydzydz** [comment]
> qpic.cn 如果使用配置中的 DNS 会导致无法加载图片，需要在 host 中加入如下片段。
> [Host]
> 
> // 微信
> *.qpic.cn = server:119.28.28.28

感谢提醒，已更新
